### ISSUE TITLE
Annotate entities

### ISSUE THREAD

**Issue by csae8092** [reading-in-the-alps/rita2-data#1]
tag person, places and books and link them to their indices (see [commit](https://github.com/reading-in-the-alps/rita2-data/commit/b553a5a150b1bc5a051dade4ab6245d140fe84fe))
1. copy the file you'd like to work with from `data/temp` to `data/editions` 
2. check if the file is valid and if not, fix it (usually wrong dates or missing from/to attributes)
3. check if from-to attributes `//tei:msItem/tei:locus` are set correct (first and last tei:pb elements)
4. check if place in `//tei:msDesc/tei:history` matches place in `//tei:title`
5. check if notBefore and notAfter matches timeframe in `//tei:title`
6. check if `//tei:msDesc/tei:msIdentifier/tei:idno` matches date in `//tei:title`
7. add `xi:include` statement to link file to `indices/listbibl.xml` (see [commit](https://github.com/reading-in-the-alps/rita2-data/commit/9ff7bc09d42bf1acc061f9f9f00ee4c46ca50b7e))
8. annotate entities **in a greedy manner**
9. delete attribute bold in book titles and page references
10. link annotations to their index-entries 
11. add `status=done` + date finished in revisionDesc

**Comment by aureon249** [comment]
https://de.wikipedia.org/wiki/Liste_der_Gemeinden_in_S%C3%BCdtirol

**Comment by aureon249** [comment]
to check: 

- people: Maria Ursulä Carl Khässer Weisgärbers zu Milbach Ehewirthin, Khachler
